# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):

    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(448, 575)
        Calculator.setMinimumSize(QtCore.QSize(448, 575))
        self.centralwidget = QtWidgets.QWidget(Calculator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setObjectName("centralwidget")
        '''self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 448, 101))
        self.lineEdit.setMinimumSize(QtCore.QSize(448, 0))
        self.lineEdit.setStyleSheet("font: 63 36pt \"Yu Gothic UI Semibold\";")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")'''
        self.Number0 = QtWidgets.QPushButton(self.centralwidget)
        self.Number0.setGeometry(QtCore.QRect(100, 490, 81, 81))
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 0, 448, 101))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setDigitCount(10)
        self.lcdNumber.setObjectName("lcdNumber")
        self.Number0.setFont(font)
        self.Number0.setObjectName("Number0")
        self.Number1 = QtWidgets.QPushButton(self.centralwidget)
        self.Number1.setGeometry(QtCore.QRect(0, 400, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number1.setFont(font)
        self.Number1.setObjectName("Number1")
        self.Number2 = QtWidgets.QPushButton(self.centralwidget)
        self.Number2.setGeometry(QtCore.QRect(100, 400, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number2.setFont(font)
        self.Number2.setObjectName("Number2")
        self.Number3 = QtWidgets.QPushButton(self.centralwidget)
        self.Number3.setGeometry(QtCore.QRect(200, 400, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number3.setFont(font)
        self.Number3.setObjectName("Number3")
        self.Number4 = QtWidgets.QPushButton(self.centralwidget)
        self.Number4.setGeometry(QtCore.QRect(0, 310, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number4.setFont(font)
        self.Number4.setObjectName("Number4")
        self.Number5 = QtWidgets.QPushButton(self.centralwidget)
        self.Number5.setGeometry(QtCore.QRect(100, 310, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number5.setFont(font)
        self.Number5.setObjectName("Number5")
        self.Number6 = QtWidgets.QPushButton(self.centralwidget)
        self.Number6.setGeometry(QtCore.QRect(200, 310, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number6.setFont(font)
        self.Number6.setObjectName("Number6")
        self.Number7 = QtWidgets.QPushButton(self.centralwidget)
        self.Number7.setGeometry(QtCore.QRect(0, 220, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number7.setFont(font)
        self.Number7.setObjectName("Number7")
        self.Number8 = QtWidgets.QPushButton(self.centralwidget)
        self.Number8.setGeometry(QtCore.QRect(100, 220, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number8.setFont(font)
        self.Number8.setObjectName("Number8")
        self.Number9 = QtWidgets.QPushButton(self.centralwidget)
        self.Number9.setGeometry(QtCore.QRect(200, 220, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Number9.setFont(font)
        self.Number9.setObjectName("Number9")
        self.parenthesis1Button = QtWidgets.QPushButton(self.centralwidget)
        self.parenthesis1Button.setGeometry(QtCore.QRect(0, 120, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.parenthesis1Button.setFont(font)
        self.parenthesis1Button.setObjectName("parenthesis1Button")
        self.Paresthesis2Button = QtWidgets.QPushButton(self.centralwidget)
        self.Paresthesis2Button.setGeometry(QtCore.QRect(100, 120, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.Paresthesis2Button.setFont(font)
        self.Paresthesis2Button.setObjectName("Paresthesis2Button")
        self.AllClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.AllClearButton.setGeometry(QtCore.QRect(200, 120, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.AllClearButton.setFont(font)
        self.AllClearButton.setObjectName("AllClearButton")
        self.PlusButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlusButton.setGeometry(QtCore.QRect(320, 220, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.PlusButton.setFont(font)
        self.PlusButton.setObjectName("PlusButton")
        self.MinusButton = QtWidgets.QPushButton(self.centralwidget)
        self.MinusButton.setGeometry(QtCore.QRect(320, 290, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.MinusButton.setFont(font)
        self.MinusButton.setObjectName("MinusButton")
        self.MultiplyButton = QtWidgets.QPushButton(self.centralwidget)
        self.MultiplyButton.setGeometry(QtCore.QRect(320, 360, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.MultiplyButton.setFont(font)
        self.MultiplyButton.setObjectName("MultiplyButton")
        self.EqualButton = QtWidgets.QPushButton(self.centralwidget)
        self.EqualButton.setGeometry(QtCore.QRect(320, 490, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.EqualButton.setFont(font)
        self.EqualButton.setObjectName("EqualButton")
        self.DeleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteButton.setGeometry(QtCore.QRect(300, 120, 131, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setObjectName("DeleteButton")
        self.DivideButton = QtWidgets.QPushButton(self.centralwidget)
        self.DivideButton.setGeometry(QtCore.QRect(320, 430, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.DivideButton.setFont(font)
        self.DivideButton.setObjectName("DivideButton")
        self.AnswerButton = QtWidgets.QPushButton(self.centralwidget)
        self.AnswerButton.setGeometry(QtCore.QRect(0, 490, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AnswerButton.setFont(font)
        self.AnswerButton.setObjectName("AnswerButton")
        self.DotButton = QtWidgets.QPushButton(self.centralwidget)
        self.DotButton.setGeometry(QtCore.QRect(200, 490, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.DotButton.setFont(font)
        self.DotButton.setObjectName("DotButton")
        Calculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.Number0.setText(_translate("Calculator", "0"))
        self.Number1.setText(_translate("Calculator", "1"))
        self.Number2.setText(_translate("Calculator", "2"))
        self.Number3.setText(_translate("Calculator", "3"))
        self.Number4.setText(_translate("Calculator", "4"))
        self.Number5.setText(_translate("Calculator", "5"))
        self.Number6.setText(_translate("Calculator", "6"))
        self.Number7.setText(_translate("Calculator", "7"))
        self.Number8.setText(_translate("Calculator", "8"))
        self.Number9.setText(_translate("Calculator", "9"))
        self.parenthesis1Button.setText(_translate("Calculator", "("))
        self.Paresthesis2Button.setText(_translate("Calculator", ")"))
        self.AllClearButton.setText(_translate("Calculator", "AC"))
        self.PlusButton.setText(_translate("Calculator", "+"))
        self.MinusButton.setText(_translate("Calculator", "-"))
        self.MultiplyButton.setText(_translate("Calculator", "X"))
        self.EqualButton.setText(_translate("Calculator", "="))
        self.DeleteButton.setText(_translate("Calculator", "DEL"))
        self.DivideButton.setText(_translate("Calculator", "÷"))
        self.AnswerButton.setText(_translate("Calculator", "ANS"))
        self.DotButton.setText(_translate("Calculator", "."))
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
